version: "3"

services:
  web:
    image: ghcr.io/holodata/holodata
    build: .
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      KAFKA_HOST: takos:9093
    extra_hosts:
      takos: ${KAFKA_REAL_IP}
    ports:
      - "3000:3000"
