version: "3"

services:
  web:
    image: ghcr.io/holodata/holodata
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: holodata.org
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: holodata.org
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      KAFKA_HOST: takos:9093
      HOLODEX_API_KEY: ${HOLODEX_API_KEY}
    # labels:
    # com.centurylinklabs.watchtower.enable: "true"
    extra_hosts:
      takos: ${KAFKA_REAL_IP}
networks:
  default:
    name: webproxy
    external: true
